# Generated by Django 4.2.7 on 2025-11-11 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ai_analysis', '0004_aianalysis_simplified_summary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='healthrecord',
            options={'ordering': ['-record_date', '-uploaded_at']},
        ),
        migrations.RemoveField(
            model_name='healthrecord',
            name='patient_id',
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
