# Generated by Django 4.2.7 on 2025-11-11 05:52

import ai_analysis.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('ai_analysis', '0005_alter_healthrecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthrecord',
            name='patient',
            field=models.ForeignKey(blank=True, db_column='patient_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='authentication.userprofile'),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='healthrecord',
            name='uploaded_by_profile',
            field=models.ForeignKey(blank=True, db_column='uploaded_by_profile_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_records', to='authentication.userprofile'),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='id',
            field=models.CharField(default=ai_analysis.models.HealthRecord.generate_uuid, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='record_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='record_type',
            field=models.CharField(choices=[('lab_test', 'Lab Test'), ('prescription', 'Prescription'), ('imaging', 'Imaging'), ('consultation', 'Consultation'), ('vaccination', 'Vaccination'), ('xray', 'X-Ray'), ('mri', 'MRI'), ('ct_scan', 'CT Scan'), ('ultrasound', 'Ultrasound'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='healthrecord',
            name='uploaded_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['patient', '-record_date'], name='health_reco_patient_bf0e96_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['record_type', '-record_date'], name='health_reco_record__9f4cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['uploaded_by_profile', '-created_at'], name='health_reco_uploade_ceb27b_idx'),
        ),
    ]
